// <auto-generated />
using System;
using Comidify.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Comidify.API.Migrations
{
    [DbContext(typeof(ComidifyDbContext))]
    [Migration("20260213122730_AddUsuariosYAuth")]
    partial class AddUsuariosYAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Comidify.API.Models.Comida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoComida")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comidas");
                });

            modelBuilder.Entity("Comidify.API.Models.ComidaIngrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cantidad")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ComidaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unidad")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComidaId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("ComidaIngredientes");
                });

            modelBuilder.Entity("Comidify.API.Models.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("Comidify.API.Models.MenuComida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComidaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuSemanalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoComida")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComidaId");

                    b.HasIndex("MenuSemanalId");

                    b.ToTable("MenuComidas");
                });

            modelBuilder.Entity("Comidify.API.Models.MenuSemanal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MenusSemanales");
                });

            modelBuilder.Entity("Comidify.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Comidify.API.Models.Comida", b =>
                {
                    b.HasOne("Comidify.API.Models.Usuario", "Usuario")
                        .WithMany("Comidas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Comidify.API.Models.ComidaIngrediente", b =>
                {
                    b.HasOne("Comidify.API.Models.Comida", "Comida")
                        .WithMany("Ingredientes")
                        .HasForeignKey("ComidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comidify.API.Models.Ingrediente", "Ingrediente")
                        .WithMany("ComidaIngredientes")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comida");

                    b.Navigation("Ingrediente");
                });

            modelBuilder.Entity("Comidify.API.Models.Ingrediente", b =>
                {
                    b.HasOne("Comidify.API.Models.Usuario", "Usuario")
                        .WithMany("Ingredientes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Comidify.API.Models.MenuComida", b =>
                {
                    b.HasOne("Comidify.API.Models.Comida", "Comida")
                        .WithMany("MenuComidas")
                        .HasForeignKey("ComidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Comidify.API.Models.MenuSemanal", "MenuSemanal")
                        .WithMany("Comidas")
                        .HasForeignKey("MenuSemanalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comida");

                    b.Navigation("MenuSemanal");
                });

            modelBuilder.Entity("Comidify.API.Models.MenuSemanal", b =>
                {
                    b.HasOne("Comidify.API.Models.Usuario", "Usuario")
                        .WithMany("MenusSemanales")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Comidify.API.Models.Comida", b =>
                {
                    b.Navigation("Ingredientes");

                    b.Navigation("MenuComidas");
                });

            modelBuilder.Entity("Comidify.API.Models.Ingrediente", b =>
                {
                    b.Navigation("ComidaIngredientes");
                });

            modelBuilder.Entity("Comidify.API.Models.MenuSemanal", b =>
                {
                    b.Navigation("Comidas");
                });

            modelBuilder.Entity("Comidify.API.Models.Usuario", b =>
                {
                    b.Navigation("Comidas");

                    b.Navigation("Ingredientes");

                    b.Navigation("MenusSemanales");
                });
#pragma warning restore 612, 618
        }
    }
}
