// <auto-generated />
using System;
using Comidify.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Comidify.API.Migrations
{
    [DbContext(typeof(ComidifyDbContext))]
    partial class ComidifyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Comidify.API.Models.Comida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TipoComida")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("Comidas");
                });

            modelBuilder.Entity("Comidify.API.Models.ComidaIngrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cantidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ComidaId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Unidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ComidaId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("ComidaIngredientes");
                });

            modelBuilder.Entity("Comidify.API.Models.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("Comidify.API.Models.MenuComida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComidaId")
                        .HasColumnType("integer");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<int>("MenuSemanalId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoComida")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComidaId");

                    b.HasIndex("MenuSemanalId", "DiaSemana", "TipoComida")
                        .IsUnique();

                    b.ToTable("MenuComidas");
                });

            modelBuilder.Entity("Comidify.API.Models.MenuSemanal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("MenusSemanales");
                });

            modelBuilder.Entity("Comidify.API.Models.ComidaIngrediente", b =>
                {
                    b.HasOne("Comidify.API.Models.Comida", "Comida")
                        .WithMany("ComidaIngredientes")
                        .HasForeignKey("ComidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comidify.API.Models.Ingrediente", "Ingrediente")
                        .WithMany("ComidaIngredientes")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comida");

                    b.Navigation("Ingrediente");
                });

            modelBuilder.Entity("Comidify.API.Models.MenuComida", b =>
                {
                    b.HasOne("Comidify.API.Models.Comida", "Comida")
                        .WithMany("MenuComidas")
                        .HasForeignKey("ComidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Comidify.API.Models.MenuSemanal", "MenuSemanal")
                        .WithMany("MenuComidas")
                        .HasForeignKey("MenuSemanalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comida");

                    b.Navigation("MenuSemanal");
                });

            modelBuilder.Entity("Comidify.API.Models.Comida", b =>
                {
                    b.Navigation("ComidaIngredientes");

                    b.Navigation("MenuComidas");
                });

            modelBuilder.Entity("Comidify.API.Models.Ingrediente", b =>
                {
                    b.Navigation("ComidaIngredientes");
                });

            modelBuilder.Entity("Comidify.API.Models.MenuSemanal", b =>
                {
                    b.Navigation("MenuComidas");
                });
#pragma warning restore 612, 618
        }
    }
}
